AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Valdrix - Read-Only IAM Role for Cost Analysis
  
  This template creates an IAM role that allows Valdrix to read
  your AWS cost data. The role uses cross-account AssumeRole with
  an External ID for security.
  
  Permissions granted:
  - Read-only inventory APIs (EC2, ELB, RDS, etc.)
  - Read-only S3 access to CUR export buckets
  - Cost Explorer access intentionally excluded to avoid API charges
  - No write access

Parameters:
  ExternalId:
    Type: String
    Description: |
      The External ID provided by Valdrix. 
      This is required for security and prevents unauthorized access.
    AllowedPattern: 'vx-[a-f0-9]{32}'
    ConstraintDescription: External ID must be in format 'vx-' followed by 32 hex characters

Resources:
  ValdrixRole:
    Type: AWS::IAM::Role
    Properties:
      Description: Allows Valdrix to read cost data for analysis
      MaxSessionDuration: 3600  # 1 hour (minimum for security)
      
      # Trust policy: Who can assume this role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              # Valdrix's AWS Account
              # In production, replace with your actual AWS account ID
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                # External ID prevents confused deputy attacks
                sts:ExternalId: !Ref ExternalId
      
      # Inline policy: What this role can do
      Policies:
        - PolicyName: ValdrixReadOnly
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # IMPORTANT: Cost Explorer APIs (ce:*) are EXPLICITLY REMOVED to prevent
              # unintended charges to the customer ($0.01/request). Valdrix MUST use
              # CUR (Cost & Usage Reports) via S3 for cost data. DO NOT re-add ce:*
              # permissions without explicit architectural approval.
              # See valdrix-cur-setup.yaml for the CUR automation template.

              
              # Read EC2 instances for zombie detection
              - Sid: EC2ReadOnly
                Effect: Allow
                Action:
                  - ec2:DescribeInstances
                  - ec2:DescribeVolumes
                  - ec2:DescribeSnapshots
                  - ec2:DescribeAddresses
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DescribeNatGateways
                  - ec2:DescribeSecurityGroups
                Resource: '*'

              - Sid: ELBReadOnly
                Effect: Allow
                Action:
                  - elasticloadbalancing:DescribeLoadBalancers
                  - elasticloadbalancing:DescribeTargetGroups
                  - elasticloadbalancing:DescribeTargetHealth
                Resource: '*'

              - Sid: RDSReadOnly
                Effect: Allow
                Action:
                  - rds:DescribeDBInstances
                  - rds:DescribeDBClusters
                Resource: '*'

              - Sid: RedshiftReadOnly
                Effect: Allow
                Action:
                  - redshift:DescribeClusters
                Resource: '*'

              - Sid: SageMakerReadOnly
                Effect: Allow
                Action:
                  - sagemaker:ListEndpoints
                  - sagemaker:ListNotebookInstances
                  - sagemaker:DescribeNotebookInstance
                  - sagemaker:ListModels
                Resource: '*'

              # EKS Cluster Detection (NEW)
              - Sid: EKSReadOnly
                Effect: Allow
                Action:
                  - eks:ListClusters
                  - eks:DescribeCluster
                  - eks:ListNodegroups
                  - eks:DescribeNodegroup
                Resource: '*'

              # ElastiCache Detection (NEW)
              - Sid: ElastiCacheReadOnly
                Effect: Allow
                Action:
                  - elasticache:DescribeCacheClusters
                  - elasticache:DescribeReplicationGroups
                Resource: '*'

              # Lambda Function Detection (NEW)
              - Sid: LambdaReadOnly
                Effect: Allow
                Action:
                  - lambda:ListFunctions
                  - lambda:GetFunction
                Resource: '*'

              # VPC Endpoint Detection (NEW)
              - Sid: VPCEndpointReadOnly
                Effect: Allow
                Action:
                  - ec2:DescribeVpcEndpoints
                Resource: '*'


              - Sid: ECRReadOnly
                Effect: Allow
                Action:
                  - ecr:DescribeRepositories
                  - ecr:DescribeImages
                Resource: '*'

              - Sid: S3ReadOnly
                Effect: Allow
                Action:
                  - s3:GetBucketLocation
                  - s3:GetBucketTagging
                Resource: '*'

              - Sid: CloudWatchRead
                Effect: Allow
                Action:
                  - cloudwatch:GetMetricData
                  - cloudwatch:GetMetricStatistics
                Resource: '*'

              # CUR Reading (Required for basic cost ingestion)
              - Sid: CURRead
                Effect: Allow
                Action:
                  - cur:DescribeReportDefinitions
                Resource: '*'

              # S3 Reading for CUR delivery (strictly mapped to Valdrix prefix)
              - Sid: S3ReadForCUR
                Effect: Allow
                Action:
                  - s3:GetBucketPolicy
                  - s3:ListBucket
                  - s3:GetObject
                Resource: 
                  - 'arn:aws:s3:::valdrix-cur-*'
                  - 'arn:aws:s3:::valdrix-cur-*/*'

              # OPTIONAL: CUR Automation (Commented out for security)
              # If you want Valdrix to automatically setup your Cost & Usage Report,
              # add the following actions to a separate policy:
              # - cur:PutReportDefinition
              # - cur:ModifyReportDefinition
              # - s3:CreateBucket
              # - s3:PutBucketPolicy


      Tags:
        - Key: Purpose
          Value: Valdrix-CostAnalysis
        - Key: ManagedBy
          Value: Valdrix

Outputs:
  RoleArn:
    Description: The ARN of the Valdrix role. Copy this to Valdrix dashboard.
    Value: !GetAtt ValdrixRole.Arn
  
