"""Deterministic cleanup for local SQLite test artifacts."""

from __future__ import annotations

from pathlib import Path

_SQLITE_ARTIFACT_PATTERNS: tuple[str, ...] = (
    "test_*.sqlite",
    "test_*.sqlite-journal",
    "test_*.sqlite-shm",
    "test_*.sqlite-wal",
    "tmp_test_*.sqlite",
    "tmp_test_*.sqlite-journal",
    "tmp_test_*.sqlite-shm",
    "tmp_test_*.sqlite-wal",
    "tmp_aiosqlite_*.sqlite",
    "tmp_aiosqlite_*.sqlite-journal",
    "tmp_aiosqlite_*.sqlite-shm",
    "tmp_aiosqlite_*.sqlite-wal",
    "tmp_sqlite3_*.sqlite",
    "tmp_sqlite3_*.sqlite-journal",
    "tmp_sqlite3_*.sqlite-shm",
    "tmp_sqlite3_*.sqlite-wal",
)


def cleanup_sqlite_test_artifacts(repo_root: Path) -> tuple[Path, ...]:
    """Delete transient SQLite files generated by tests under repo root."""
    deleted: list[Path] = []
    seen: set[Path] = set()

    for pattern in _SQLITE_ARTIFACT_PATTERNS:
        for path in repo_root.glob(pattern):
            if path in seen or not path.is_file():
                continue
            seen.add(path)
            path.unlink(missing_ok=True)
            deleted.append(path)

    return tuple(sorted(deleted))

