"""add_llm_provider_pricing_table_v3

Revision ID: 1db8130b8ee6
Revises: p14_sec_hardening
Create Date: 2026-02-09 00:36:09.370641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1db8130b8ee6'
down_revision: Union[str, Sequence[str], None] = 'p14_sec_hardening'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_provider_pricing',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('input_cost_per_million', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('output_cost_per_million', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('free_tier_tokens', sa.Numeric(precision=20, scale=0), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_provider_pricing_model'), 'llm_provider_pricing', ['model'], unique=False)
    op.create_index(op.f('ix_llm_provider_pricing_provider'), 'llm_provider_pricing', ['provider'], unique=False)
    op.create_table('optimization_strategies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attribution_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.String(), nullable=False),
    sa.Column('conditions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('allocation', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attribution_rules_tenant_id'), 'attribution_rules', ['tenant_id'], unique=False)
    op.create_table('strategy_recommendations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('strategy_id', sa.Uuid(), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('term', sa.String(length=20), nullable=False),
    sa.Column('payment_option', sa.String(length=20), nullable=False),
    sa.Column('upfront_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monthly_recurring_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estimated_monthly_savings', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('roi_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['optimization_strategies.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_recommendations_tenant_id'), 'strategy_recommendations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_strategy_recommendations_strategy_id'), 'strategy_recommendations', ['strategy_id'], unique=False)
    op.create_table('cost_allocations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cost_record_id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.Date(), nullable=False),
    sa.Column('rule_id', sa.Uuid(), nullable=True),
    sa.Column('allocated_to', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cost_record_id', 'recorded_at'], ['cost_records.id', 'cost_records.recorded_at'], name='fk_cost_allocations_cost_record'),
    sa.ForeignKeyConstraint(['rule_id'], ['attribution_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_allocations_allocated_to'), 'cost_allocations', ['allocated_to'], unique=False)
    op.create_index(op.f('ix_cost_allocations_cost_record_id'), 'cost_allocations', ['cost_record_id'], unique=False)
    op.create_index(op.f('ix_cost_allocations_recorded_at'), 'cost_allocations', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_cost_allocations_timestamp'), 'cost_allocations', ['timestamp'], unique=False)
    op.create_index(op.f('ix_cost_allocations_rule_id'), 'cost_allocations', ['rule_id'], unique=False)
    op.create_index('ix_cost_allocations_composite_record', 'cost_allocations', ['cost_record_id', 'recorded_at'], unique=False)
    op.drop_index(op.f('cost_records_archive_recorded_at_idx'), table_name='cost_records_archive')
    op.drop_index(op.f('cost_records_archive_service_idx'), table_name='cost_records_archive')
    op.drop_index(op.f('cost_records_archive_tenant_id_idx'), table_name='cost_records_archive')
    op.drop_index(op.f('cost_records_archive_timestamp_idx'), table_name='cost_records_archive')
    op.drop_table('cost_records_archive')
    op.alter_column('anomaly_markers', 'exclude_from_training',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('anomaly_markers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_anomaly_markers_date_range'), table_name='anomaly_markers')
    op.alter_column('aws_connections', 'is_management_account',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('cloud_accounts', 'credentials_encrypted')
    op.add_column('cost_records', sa.Column('is_preliminary', sa.Boolean(), nullable=False))
    op.add_column('cost_records', sa.Column('cost_status', sa.String(), nullable=False))
    op.add_column('cost_records', sa.Column('reconciliation_run_id', sa.Uuid(), nullable=True))
    op.add_column('cost_records', sa.Column('ingestion_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('cost_records', sa.Column('attribution_id', sa.Uuid(), nullable=True))
    op.add_column('cost_records', sa.Column('allocated_to', sa.String(), nullable=True))
    op.create_index(op.f('ix_cost_records_allocated_to'), 'cost_records', ['allocated_to'], unique=False)
    op.create_index(op.f('ix_cost_records_attribution_id'), 'cost_records', ['attribution_id'], unique=False)
    op.create_index(op.f('ix_cost_records_cost_status'), 'cost_records', ['cost_status'], unique=False)
    op.create_index(op.f('ix_cost_records_is_preliminary'), 'cost_records', ['is_preliminary'], unique=False)
    op.create_index(op.f('ix_cost_records_reconciliation_run_id'), 'cost_records', ['reconciliation_run_id'], unique=False)
    op.create_foreign_key('fk_cost_records_attribution', 'cost_records', 'attribution_rules', ['attribution_id'], ['id'])
    op.add_column('llm_usage', sa.Column('operation_id', sa.String(length=36), nullable=True))
    op.add_column('llm_usage', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_llm_usage_created_at'), 'llm_usage', ['created_at'], unique=False)
    op.create_index(op.f('ix_llm_usage_operation_id'), 'llm_usage', ['operation_id'], unique=False)
    op.add_column('notification_settings', sa.Column('alert_on_carbon_budget_warning', sa.Boolean(), nullable=False))
    op.add_column('notification_settings', sa.Column('alert_on_carbon_budget_exceeded', sa.Boolean(), nullable=False))
    op.add_column('remediation_requests', sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('remediation_requests', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('remediation_requests', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('remediation_requests', 'create_backup',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('remediation_requests', 'backup_retention_days',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_remediation_requests_created_at'), 'remediation_requests', ['created_at'], unique=False)
    op.alter_column('tenant_subscriptions', 'dunning_attempts',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=2, scale=0),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('tenants', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tenants', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tenant_subscriptions', 'dunning_attempts',
               existing_type=sa.Numeric(precision=2, scale=0),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_remediation_requests_created_at'), table_name='remediation_requests')
    op.alter_column('remediation_requests', 'backup_retention_days',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('remediation_requests', 'create_backup',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('remediation_requests', 'updated_at')
    op.drop_column('remediation_requests', 'created_at')
    op.drop_column('remediation_requests', 'executed_at')
    op.drop_column('notification_settings', 'alert_on_carbon_budget_exceeded')
    op.drop_column('notification_settings', 'alert_on_carbon_budget_warning')
    op.drop_index(op.f('ix_llm_usage_operation_id'), table_name='llm_usage')
    op.drop_index(op.f('ix_llm_usage_created_at'), table_name='llm_usage')
    op.drop_column('llm_usage', 'created_at')
    op.drop_column('llm_usage', 'operation_id')
    op.drop_constraint('fk_cost_records_attribution', 'cost_records', type_='foreignkey')
    op.drop_index(op.f('ix_cost_records_reconciliation_run_id'), table_name='cost_records')
    op.drop_index(op.f('ix_cost_records_is_preliminary'), table_name='cost_records')
    op.drop_index(op.f('ix_cost_records_cost_status'), table_name='cost_records')
    op.drop_index(op.f('ix_cost_records_attribution_id'), table_name='cost_records')
    op.drop_index(op.f('ix_cost_records_allocated_to'), table_name='cost_records')
    op.drop_column('cost_records', 'allocated_to')
    op.drop_column('cost_records', 'attribution_id')
    op.drop_column('cost_records', 'ingestion_metadata')
    op.drop_column('cost_records', 'reconciliation_run_id')
    op.drop_column('cost_records', 'cost_status')
    op.drop_column('cost_records', 'is_preliminary')
    op.add_column('cloud_accounts', sa.Column('credentials_encrypted', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('aws_connections', 'is_management_account',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_anomaly_markers_date_range'), 'anomaly_markers', ['tenant_id', 'start_date', 'end_date'], unique=False)
    op.alter_column('anomaly_markers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('anomaly_markers', 'exclude_from_training',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_table('cost_records_archive',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('service', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('usage_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cost_usd', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('amount_raw', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('carbon_kg', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('recorded_at', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('archived_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', 'recorded_at', name=op.f('cost_records_archive_pkey')),
    sa.UniqueConstraint('account_id', 'timestamp', 'service', 'region', 'usage_type', 'recorded_at', name=op.f('cost_records_archive_account_id_timestamp_service_region_us_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    comment='Archive table for cost_records partitions older than 1 year. \n         Use archive_old_cost_partitions() function to move old data here.'
    )
    op.create_index(op.f('cost_records_archive_timestamp_idx'), 'cost_records_archive', ['timestamp'], unique=False)
    op.create_index(op.f('cost_records_archive_tenant_id_idx'), 'cost_records_archive', ['tenant_id'], unique=False)
    op.create_index(op.f('cost_records_archive_service_idx'), 'cost_records_archive', ['service'], unique=False)
    op.create_index(op.f('cost_records_archive_recorded_at_idx'), 'cost_records_archive', ['recorded_at'], unique=False)
    op.drop_index(op.f('ix_cost_allocations_timestamp'), table_name='cost_allocations')
    op.drop_index(op.f('ix_cost_allocations_recorded_at'), table_name='cost_allocations')
    op.drop_index(op.f('ix_cost_allocations_cost_record_id'), table_name='cost_allocations')
    op.drop_index(op.f('ix_cost_allocations_allocated_to'), table_name='cost_allocations')
    op.drop_table('cost_allocations')
    op.drop_index(op.f('ix_strategy_recommendations_tenant_id'), table_name='strategy_recommendations')
    op.drop_table('strategy_recommendations')
    op.drop_index(op.f('ix_attribution_rules_tenant_id'), table_name='attribution_rules')
    op.drop_table('attribution_rules')
    op.drop_table('optimization_strategies')
    op.drop_index(op.f('ix_llm_provider_pricing_provider'), table_name='llm_provider_pricing')
    op.drop_index(op.f('ix_llm_provider_pricing_model'), table_name='llm_provider_pricing')
    op.drop_table('llm_provider_pricing')
    # ### end Alembic commands ###
