"""Add is_deleted to BackgroundJob

Revision ID: 844ca0dfb7a7
Revises: ac78ce137d62
Create Date: 2026-01-18 06:39:13.266241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '844ca0dfb7a7'
down_revision: Union[str, Sequence[str], None] = 'ac78ce137d62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('cost_records_2026_03_service_idx'), table_name='cost_records_2026_03')
    op.drop_index(op.f('cost_records_2026_03_tenant_id_idx'), table_name='cost_records_2026_03')
    op.drop_table('cost_records_2026_03')
    op.drop_table('audit_logs_2026_01')
    op.drop_table('audit_logs')
    op.drop_index(op.f('cost_records_default_service_idx'), table_name='cost_records_default')
    op.drop_index(op.f('cost_records_default_tenant_id_idx'), table_name='cost_records_default')
    op.drop_table('cost_records_default')
    op.drop_index(op.f('cost_records_2026_02_service_idx'), table_name='cost_records_2026_02')
    op.drop_index(op.f('cost_records_2026_02_tenant_id_idx'), table_name='cost_records_2026_02')
    op.drop_table('cost_records_2026_02')
    op.drop_table('audit_logs_default')
    op.drop_table('audit_logs_2026_03')
    op.drop_index(op.f('cost_records_2026_01_service_idx'), table_name='cost_records_2026_01')
    op.drop_index(op.f('cost_records_2026_01_tenant_id_idx'), table_name='cost_records_2026_01')
    op.drop_table('cost_records_2026_01')
    op.drop_table('audit_logs_2026_02')
    op.create_unique_constraint('uq_tenant_aws_account', 'aws_connections', ['tenant_id', 'aws_account_id'])
    op.drop_column('aws_connections', 'updated_at')
    op.drop_column('aws_connections', 'created_at')
    op.add_column('background_jobs', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.alter_column('background_jobs', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('background_jobs', 'attempts',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('background_jobs', 'max_attempts',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('3'))
    op.alter_column('background_jobs', 'scheduled_for',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('background_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_background_jobs_created_at'), 'background_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_background_jobs_is_deleted'), 'background_jobs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_background_jobs_status'), 'background_jobs', ['status'], unique=False)
    op.drop_column('cloud_accounts', 'updated_at')
    op.drop_column('cloud_accounts', 'created_at')
    op.alter_column('cost_records', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'USD'::character varying"))
    op.create_index(op.f('ix_cost_records_recorded_at'), 'cost_records', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_cost_records_timestamp'), 'cost_records', ['timestamp'], unique=False)
    op.create_foreign_key(None, 'cost_records', 'cloud_accounts', ['account_id'], ['id'])
    op.create_foreign_key(None, 'cost_records', 'tenants', ['tenant_id'], ['id'])
    op.drop_column('cost_records', 'updated_at')
    op.drop_column('cost_records', 'created_at')
    op.drop_constraint(op.f('discovered_accounts_tenant_id_fkey'), 'discovered_accounts', type_='foreignkey')
    op.drop_column('discovered_accounts', 'tenant_id')
    op.drop_column('discovered_accounts', 'updated_at')
    op.drop_column('discovered_accounts', 'created_at')
    op.drop_column('exchange_rates', 'updated_at')
    op.drop_column('exchange_rates', 'created_at')
    op.drop_column('llm_budgets', 'updated_at')
    op.drop_column('llm_budgets', 'created_at')
    op.drop_column('llm_usage', 'updated_at')
    op.drop_column('llm_usage', 'created_at')
    op.drop_column('notification_settings', 'updated_at')
    op.drop_column('notification_settings', 'created_at')
    op.drop_column('pricing_plans', 'updated_at')
    op.drop_column('pricing_plans', 'created_at')
    op.alter_column('remediation_requests', 'requested_by_user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('ix_remediation_tenant_resource', 'remediation_requests', ['tenant_id', 'resource_id'], unique=False)
    op.drop_column('remediation_requests', 'updated_at')
    op.drop_column('remediation_requests', 'created_at')
    op.drop_column('remediation_settings', 'updated_at')
    op.drop_column('remediation_settings', 'created_at')
    op.drop_index(op.f('idx_tenant_subscriptions_tenant_id'), table_name='tenant_subscriptions')
    op.drop_constraint(op.f('tenant_subscriptions_tenant_id_key'), 'tenant_subscriptions', type_='unique')
    op.create_index(op.f('ix_tenant_subscriptions_tenant_id'), 'tenant_subscriptions', ['tenant_id'], unique=True)
    op.drop_column('tenants', 'updated_at')
    op.drop_column('tenants', 'created_at')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint('uq_tenant_user_email', 'users', ['tenant_id', 'email_bidx'])
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint('uq_tenant_user_email', 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('tenants', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('tenants', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_tenant_subscriptions_tenant_id'), table_name='tenant_subscriptions')
    op.create_unique_constraint(op.f('tenant_subscriptions_tenant_id_key'), 'tenant_subscriptions', ['tenant_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_tenant_subscriptions_tenant_id'), 'tenant_subscriptions', ['tenant_id'], unique=False)
    op.add_column('remediation_settings', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('remediation_settings', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('remediation_requests', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('remediation_requests', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_index('ix_remediation_tenant_resource', table_name='remediation_requests')
    op.alter_column('remediation_requests', 'requested_by_user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('pricing_plans', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('pricing_plans', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('notification_settings', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('notification_settings', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('llm_usage', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('llm_usage', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('llm_budgets', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('llm_budgets', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('exchange_rates', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('exchange_rates', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('discovered_accounts', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('discovered_accounts', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('discovered_accounts', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('discovered_accounts_tenant_id_fkey'), 'discovered_accounts', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('cost_records', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('cost_records', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cost_records', type_='foreignkey')
    op.drop_constraint(None, 'cost_records', type_='foreignkey')
    op.drop_index(op.f('ix_cost_records_timestamp'), table_name='cost_records')
    op.drop_index(op.f('ix_cost_records_recorded_at'), table_name='cost_records')
    op.alter_column('cost_records', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'USD'::character varying"))
    op.add_column('cloud_accounts', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('cloud_accounts', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_background_jobs_status'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_is_deleted'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_created_at'), table_name='background_jobs')
    op.alter_column('background_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('background_jobs', 'scheduled_for',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('background_jobs', 'max_attempts',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('3'))
    op.alter_column('background_jobs', 'attempts',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('background_jobs', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_column('background_jobs', 'is_deleted')
    op.add_column('aws_connections', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('aws_connections', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint('uq_tenant_aws_account', 'aws_connections', type_='unique')
    op.create_table('audit_logs_2026_02',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('event_timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('actor_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('actor_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('actor_ip', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('correlation_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('request_method', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('request_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('resource_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', 'event_timestamp', name=op.f('audit_logs_2026_02_pkey'))
    )
    op.create_table('cost_records_2026_01',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('service', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('usage_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cost_usd', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('amount_raw', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(), server_default=sa.text("'USD'::character varying"), autoincrement=False, nullable=True),
    sa.Column('carbon_kg', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('recorded_at', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', 'recorded_at', name=op.f('cost_records_2026_01_pkey')),
    sa.UniqueConstraint('account_id', 'timestamp', 'service', 'region', 'usage_type', 'recorded_at', name=op.f('cost_records_2026_01_account_id_timestamp_service_region_us_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('cost_records_2026_01_tenant_id_idx'), 'cost_records_2026_01', ['tenant_id'], unique=False)
    op.create_index(op.f('cost_records_2026_01_service_idx'), 'cost_records_2026_01', ['service'], unique=False)
    op.create_table('audit_logs_2026_03',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('event_timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('actor_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('actor_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('actor_ip', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('correlation_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('request_method', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('request_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('resource_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', 'event_timestamp', name=op.f('audit_logs_2026_03_pkey'))
    )
    op.create_table('audit_logs_default',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('event_timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('actor_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('actor_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('actor_ip', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('correlation_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('request_method', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('request_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('resource_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', 'event_timestamp', name=op.f('audit_logs_default_pkey'))
    )
    op.create_table('cost_records_2026_02',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('service', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('usage_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cost_usd', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('amount_raw', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(), server_default=sa.text("'USD'::character varying"), autoincrement=False, nullable=True),
    sa.Column('carbon_kg', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('recorded_at', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', 'recorded_at', name=op.f('cost_records_2026_02_pkey')),
    sa.UniqueConstraint('account_id', 'timestamp', 'service', 'region', 'usage_type', 'recorded_at', name=op.f('cost_records_2026_02_account_id_timestamp_service_region_us_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('cost_records_2026_02_tenant_id_idx'), 'cost_records_2026_02', ['tenant_id'], unique=False)
    op.create_index(op.f('cost_records_2026_02_service_idx'), 'cost_records_2026_02', ['service'], unique=False)
    op.create_table('cost_records_default',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('service', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('usage_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cost_usd', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('amount_raw', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(), server_default=sa.text("'USD'::character varying"), autoincrement=False, nullable=True),
    sa.Column('carbon_kg', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('recorded_at', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', 'recorded_at', name=op.f('cost_records_default_pkey')),
    sa.UniqueConstraint('account_id', 'timestamp', 'service', 'region', 'usage_type', 'recorded_at', name=op.f('cost_records_default_account_id_timestamp_service_region_us_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('cost_records_default_tenant_id_idx'), 'cost_records_default', ['tenant_id'], unique=False)
    op.create_index(op.f('cost_records_default_service_idx'), 'cost_records_default', ['service'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('event_timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('actor_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('actor_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('actor_ip', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('correlation_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('request_method', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('request_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('resource_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', 'event_timestamp', name=op.f('audit_logs_pkey'))
    )
    op.create_table('audit_logs_2026_01',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('event_timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('actor_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('actor_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('actor_ip', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('correlation_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('request_method', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('request_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('resource_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', 'event_timestamp', name=op.f('audit_logs_2026_01_pkey'))
    )
    op.create_table('cost_records_2026_03',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('service', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('usage_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cost_usd', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('amount_raw', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(), server_default=sa.text("'USD'::character varying"), autoincrement=False, nullable=True),
    sa.Column('carbon_kg', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('recorded_at', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', 'recorded_at', name=op.f('cost_records_2026_03_pkey')),
    sa.UniqueConstraint('account_id', 'timestamp', 'service', 'region', 'usage_type', 'recorded_at', name=op.f('cost_records_2026_03_account_id_timestamp_service_region_us_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('cost_records_2026_03_tenant_id_idx'), 'cost_records_2026_03', ['tenant_id'], unique=False)
    op.create_index(op.f('cost_records_2026_03_service_idx'), 'cost_records_2026_03', ['service'], unique=False)
    # ### end Alembic commands ###
