"""sync model schema drift

Revision ID: 99d8bf8028a2
Revises: 7c8d9e0f1a2b
Create Date: 2026-02-20 15:40:09.690038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99d8bf8028a2'
down_revision: Union[str, Sequence[str], None] = '7c8d9e0f1a2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aws_connections', sa.Column('is_production', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('aws_connections', sa.Column('cur_prefix', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_aws_connections_is_production'), 'aws_connections', ['is_production'], unique=False)
    op.create_unique_constraint('uq_tenant_aws_account', 'aws_connections', ['tenant_id', 'aws_account_id'])
    op.add_column('azure_connections', sa.Column('is_production', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('azure_connections', sa.Column('auth_method', sa.String(), server_default='secret', nullable=False))
    op.alter_column('azure_connections', 'client_secret',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('azure_connections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('azure_connections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_azure_connections_is_production'), 'azure_connections', ['is_production'], unique=False)
    op.create_index('ix_cost_records_tenant_recorded', 'cost_records', ['tenant_id', 'recorded_at'], unique=False)
    op.add_column('gcp_connections', sa.Column('is_production', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('gcp_connections', sa.Column('auth_method', sa.String(), server_default='secret', nullable=False))
    op.add_column('gcp_connections', sa.Column('billing_project_id', sa.String(), nullable=True))
    op.add_column('gcp_connections', sa.Column('billing_dataset', sa.String(), nullable=True))
    op.add_column('gcp_connections', sa.Column('billing_table', sa.String(), nullable=True))
    op.alter_column('gcp_connections', 'service_account_json',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('gcp_connections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('gcp_connections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_gcp_connections_is_production'), 'gcp_connections', ['is_production'], unique=False)
    op.add_column('tenants', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tenants', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_tenants_deleted_at'), 'tenants', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_tenants_is_deleted'), 'tenants', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_is_deleted'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_deleted_at'), table_name='tenants')
    op.drop_column('tenants', 'is_deleted')
    op.drop_column('tenants', 'deleted_at')
    op.drop_index(op.f('ix_gcp_connections_is_production'), table_name='gcp_connections')
    op.alter_column('gcp_connections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('gcp_connections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('gcp_connections', 'service_account_json',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('gcp_connections', 'billing_table')
    op.drop_column('gcp_connections', 'billing_dataset')
    op.drop_column('gcp_connections', 'billing_project_id')
    op.drop_column('gcp_connections', 'auth_method')
    op.drop_column('gcp_connections', 'is_production')
    op.drop_index('ix_cost_records_tenant_recorded', table_name='cost_records')
    op.drop_index(op.f('ix_azure_connections_is_production'), table_name='azure_connections')
    op.alter_column('azure_connections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('azure_connections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('azure_connections', 'client_secret',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('azure_connections', 'auth_method')
    op.drop_column('azure_connections', 'is_production')
    op.drop_constraint('uq_tenant_aws_account', 'aws_connections', type_='unique')
    op.drop_index(op.f('ix_aws_connections_is_production'), table_name='aws_connections')
    op.drop_column('aws_connections', 'cur_prefix')
    op.drop_column('aws_connections', 'is_production')
    # ### end Alembic commands ###
