"""Add remediation requests table

Revision ID: 9ec1f3bc2370
Revises: 6e0db32e8ee9
Create Date: 2026-01-08 23:07:20.765490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ec1f3bc2370'
down_revision: Union[str, Sequence[str], None] = '6e0db32e8ee9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remediation_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=20), nullable=False),
    sa.Column('action', sa.Enum('DELETE_VOLUME', 'DELETE_SNAPSHOT', 'RELEASE_ELASTIC_IP', 'STOP_INSTANCE', 'TERMINATE_INSTANCE', name='remediationaction'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'EXECUTING', 'COMPLETED', 'FAILED', 'REJECTED', 'CANCELLED', name='remediationstatus'), nullable=False),
    sa.Column('estimated_monthly_savings', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('create_backup', sa.Boolean(), nullable=True),
    sa.Column('backup_retention_days', sa.Integer(), nullable=True),
    sa.Column('backup_resource_id', sa.String(length=100), nullable=True),
    sa.Column('backup_cost_estimate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('requested_by_user_id', sa.UUID(), nullable=False),
    sa.Column('reviewed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('review_notes', sa.String(length=500), nullable=True),
    sa.Column('execution_error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], name=op.f('fk_remediation_requests_requested_by_user_id_users')),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], name=op.f('fk_remediation_requests_reviewed_by_user_id_users')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_remediation_requests_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_remediation_requests'))
    )
    op.create_index(op.f('ix_remediation_requests_resource_id'), 'remediation_requests', ['resource_id'], unique=False)
    op.create_index(op.f('ix_remediation_requests_status'), 'remediation_requests', ['status'], unique=False)
    op.create_index(op.f('ix_remediation_requests_tenant_id'), 'remediation_requests', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_remediation_requests_tenant_id'), table_name='remediation_requests')
    op.drop_index(op.f('ix_remediation_requests_status'), table_name='remediation_requests')
    op.drop_index(op.f('ix_remediation_requests_resource_id'), table_name='remediation_requests')
    op.drop_table('remediation_requests')
    # ### end Alembic commands ###
