"""add_aws_organizations_support

Revision ID: bb772b6f1c3b
Revises: f62cfab1b4fd
Create Date: 2026-01-15 19:41:16.784113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb772b6f1c3b'
down_revision: Union[str, Sequence[str], None] = 'f62cfab1b4fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovered_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('management_connection_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='discovered', nullable=False),
    sa.Column('last_discovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['management_connection_id'], ['aws_connections.id'], name=op.f('fk_discovered_accounts_management_connection_id_aws_connections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discovered_accounts'))
    )
    op.create_index(op.f('ix_discovered_accounts_management_connection_id'), 'discovered_accounts', ['management_connection_id'], unique=False)
    op.drop_index(op.f('ix_gcp_connections_tenant_id'), table_name='gcp_connections')
    op.drop_table('gcp_connections')
    op.drop_index(op.f('ix_azure_connections_tenant_id'), table_name='azure_connections')
    op.drop_table('azure_connections')
    op.drop_index(op.f('ix_jobs_status_scheduled'), table_name='background_jobs', postgresql_where="((status)::text = 'pending'::text)")
    op.drop_index(op.f('ix_jobs_tenant'), table_name='background_jobs')
    op.drop_index(op.f('ix_jobs_type'), table_name='background_jobs')
    op.drop_table('background_jobs')
    op.add_column('aws_connections', sa.Column('is_management_account', sa.Boolean(), server_default='false', nullable=True))
    op.add_column('aws_connections', sa.Column('organization_id', sa.String(length=32), nullable=True))
    op.alter_column('aws_connections', 'last_verified_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('cost_records', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'USD'::character varying"))
    op.add_column('remediation_requests', sa.Column('provider', sa.String(length=20), nullable=False))
    op.add_column('remediation_requests', sa.Column('connection_id', sa.UUID(), nullable=True))
    op.alter_column('tenants', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tenants', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('remediation_requests', 'connection_id')
    op.drop_column('remediation_requests', 'provider')
    op.alter_column('cost_records', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'USD'::character varying"))
    op.alter_column('aws_connections', 'last_verified_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('aws_connections', 'organization_id')
    op.drop_column('aws_connections', 'is_management_account')
    op.create_table('background_jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('job_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('attempts', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('max_attempts', sa.INTEGER(), server_default=sa.text('3'), autoincrement=False, nullable=False),
    sa.Column('scheduled_for', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_background_jobs_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_background_jobs'))
    )
    op.create_index(op.f('ix_jobs_type'), 'background_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_jobs_tenant'), 'background_jobs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_jobs_status_scheduled'), 'background_jobs', ['status', 'scheduled_for'], unique=False, postgresql_where="((status)::text = 'pending'::text)")
    op.create_table('azure_connections',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('azure_tenant_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('subscription_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('client_secret', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('last_synced_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_ingested_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_azure_connections_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_azure_connections'))
    )
    op.create_index(op.f('ix_azure_connections_tenant_id'), 'azure_connections', ['tenant_id'], unique=False)
    op.create_table('gcp_connections',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('service_account_json', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('last_synced_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_ingested_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_gcp_connections_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gcp_connections'))
    )
    op.create_index(op.f('ix_gcp_connections_tenant_id'), 'gcp_connections', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_discovered_accounts_management_connection_id'), table_name='discovered_accounts')
    op.drop_table('discovered_accounts')
    # ### end Alembic commands ###
