"""make_requested_by_user_id_non_nullable

Revision ID: ca9dc8eed6e0
Revises: 31a34604efe0
Create Date: 2026-01-19 02:47:20.779896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca9dc8eed6e0'
down_revision: Union[str, Sequence[str], None] = '31a34604efe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    # ### commands auto generated by Alembic - please adjust! ###
    if 'exchange_rates' not in tables:
        op.create_table('exchange_rates',
        sa.Column('from_currency', sa.String(length=3), nullable=False),
        sa.Column('to_currency', sa.String(length=3), nullable=False),
        sa.Column('rate', sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column('provider', sa.String(length=50), nullable=False),
        sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('from_currency', 'to_currency')
        )
    
    if 'pricing_plans' not in tables:
        op.create_table('pricing_plans',
        sa.Column('id', sa.String(length=50), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.String(length=500), nullable=True),
        sa.Column('price_usd', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('limits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('display_features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('cta_text', sa.String(length=50), nullable=False),
        sa.Column('is_popular', sa.Boolean(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    
    if 'tenant_subscriptions' not in tables:
        op.create_table('tenant_subscriptions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('paystack_customer_code', sa.String(length=255), nullable=True),
        sa.Column('paystack_subscription_code', sa.String(length=255), nullable=True),
        sa.Column('paystack_email_token', sa.String(length=255), nullable=True),
        sa.Column('paystack_auth_code', sa.String(length=255), nullable=True),
        sa.Column('tier', sa.String(length=20), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('next_payment_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_tenant_subscriptions_tenant_id'), 'tenant_subscriptions', ['tenant_id'], unique=True)
    if 'audit_logs' in tables:
        indices = [idx['name'] for idx in inspector.get_indexes('audit_logs')]
        for idx in ['ix_audit_logs_correlation_id', 'ix_audit_logs_event_timestamp', 'ix_audit_logs_event_type', 'ix_audit_logs_tenant_id', 'ix_audit_tenant_time', 'ix_audit_type_time']:
            if idx in indices:
                op.drop_index(op.f(idx), table_name='audit_logs')
        op.drop_table('audit_logs')

    if 'azure_connections' in tables:
        op.create_unique_constraint('uq_tenant_azure_subscription', 'azure_connections', ['tenant_id', 'subscription_id'])
    
    if 'background_jobs' in tables:
        cols = [c['name'] for c in inspector.get_columns('background_jobs')]
        if 'priority' not in cols:
            op.add_column('background_jobs', sa.Column('priority', sa.Integer(), nullable=False, server_default='0'))
            op.create_index(op.f('ix_background_jobs_priority'), 'background_jobs', ['priority'], unique=False)
    
    if 'gcp_connections' in tables:
        op.create_unique_constraint('uq_tenant_gcp_project', 'gcp_connections', ['tenant_id', 'project_id'])
    
    if 'remediation_requests' in tables:
        cols = [c['name'] for c in inspector.get_columns('remediation_requests')]
        if 'scheduled_execution_at' not in cols:
            op.add_column('remediation_requests', sa.Column('scheduled_execution_at', sa.DateTime(timezone=True), nullable=True))
            op.create_index(op.f('ix_remediation_requests_scheduled_execution_at'), 'remediation_requests', ['scheduled_execution_at'], unique=False)
        op.alter_column('remediation_requests', 'requested_by_user_id',
                   existing_type=sa.UUID(),
                   nullable=False)
    
    if 'remediation_settings' in tables:
        cols = [c['name'] for c in inspector.get_columns('remediation_settings')]
        if 'hard_cap_enabled' not in cols:
            op.add_column('remediation_settings', sa.Column('hard_cap_enabled', sa.Boolean(), nullable=False, server_default='false'))
        if 'monthly_hard_cap_usd' not in cols:
            op.add_column('remediation_settings', sa.Column('monthly_hard_cap_usd', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('remediation_settings', 'monthly_hard_cap_usd')
    op.drop_column('remediation_settings', 'hard_cap_enabled')
    op.drop_index(op.f('ix_remediation_requests_scheduled_execution_at'), table_name='remediation_requests')
    op.alter_column('remediation_requests', 'requested_by_user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('remediation_requests', 'scheduled_execution_at')
    op.drop_constraint('uq_tenant_gcp_project', 'gcp_connections', type_='unique')
    op.drop_index(op.f('ix_background_jobs_priority'), table_name='background_jobs')
    op.drop_column('background_jobs', 'priority')
    op.drop_constraint('uq_tenant_azure_subscription', 'azure_connections', type_='unique')
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('event_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('actor_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('actor_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('actor_ip', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('correlation_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('request_method', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('request_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('resource_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('audit_logs_actor_id_fkey')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('audit_logs_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'event_timestamp', name=op.f('audit_logs_pkey'))
    )
    op.create_index(op.f('ix_audit_type_time'), 'audit_logs', ['event_type', 'event_timestamp'], unique=False)
    op.create_index(op.f('ix_audit_tenant_time'), 'audit_logs', ['tenant_id', 'event_timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_timestamp'), 'audit_logs', ['event_timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_correlation_id'), 'audit_logs', ['correlation_id'], unique=False)
    op.drop_index(op.f('ix_tenant_subscriptions_tenant_id'), table_name='tenant_subscriptions')
    op.drop_table('tenant_subscriptions')
    op.drop_table('pricing_plans')
    op.drop_table('exchange_rates')
    # ### end Alembic commands ###
